DROP TABLE `#__swjprojects_versions`;
DROP TABLE `#__swjprojects_projects`;
DROP TABLE `#__swjprojects_keys`;
DROP TABLE `#__swjprojects_documentation`;
DROP TABLE `#__swjprojects_categories`;
DROP TABLE `#__swjprojects_translate_versions`;
DROP TABLE `#__swjprojects_translate_projects`;
DROP TABLE `#__swjprojects_translate_categories`;
DROP TABLE `#__swjprojects_projects_categories`;